## install pg_bouncer 

- name: Install curl and ca-certificates
  ansible.builtin.apt:
    name:
      - curl
      - ca-certificates
    state: present
    update_cache: yes

- name: Create pgdg directory
  ansible.builtin.file:
    path: /usr/share/postgresql-common/pgdg
    state: directory
    mode: '0755'

- name: Download PostgreSQL GPG key
  ansible.builtin.get_url:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    dest: /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc
    mode: '0644'

- name: Add PostgreSQL APT repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt {{ ansible_lsb.codename }}-pgdg main"
    state: present
    filename: pgdg
    update_cache: yes

- name: Install pgbouncer
  ansible.builtin.apt:
    name: pgbouncer
    state: present

- name: Copy pgbouncer configuration file
  ansible.builtin.template:
    src: pgbouncer.ini.j2
    dest: /etc/pgbouncer/pgbouncer.ini
    mode: '0640'
    owner: postgres
    group: postgres
    notify: Restart pgbouncer

- name: Copy pgbouncer user list file
  ansible.builtin.template:
    src: userlist.txt.j2
    dest: /etc/pgbouncer/userlist.txt
    mode: '0640'
    owner: postgres
    group: postgres
    notify: Restart pgbouncer
