---
# tasks file for preinstall

- name: Install docker packages
  include_tasks: docker.yml

- name: Update apt chache
  apt:
    update_cache: yes

- name: Upgrade packages
  apt:
    update_cache: yes
    upgrade: yes

- name: Install packages
  apt:
    pkg:
      - postgresql-14
      - postgresql-contrib-14
      - python3-pip
      - python3-dev
      - libpq-dev
      - etcd
      - gcc
      - jq
      - curl
      - git
      - vim
      - nload
    state: present

- name: Stop postgresql-14 service
  service:
    name: postgresql
    state: stopped

- name: Stop and disable etcd service
  service:
    name: etcd
    state: stopped
    enabled: false

- name: Add hosts to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item].private_ip }} {{ item }}"
    state: present
  loop: "{{ groups['all'] }}"
  when: hostvars[item].private_ip is defined

- name: List PostgreSQL binaries
  ansible.builtin.find:
    paths: /usr/lib/postgresql/14/bin/
    patterns: '*'
    file_type: file
  register: postgres_binaries

- name: Create symbolic links
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "/usr/sbin/{{ item.path | basename }}"
    state: link
  loop: "{{ postgres_binaries.files }}"

- name: Install and upgrade pip
  pip:
    name: pip
    extra_args: --upgrade
    executable: pip3

- name: Install pip packages
  pip:
    name:
      - patroni
      - python-etcd
      - psycopg2
    state: present
